spring:
    application:
        name: sales-service
    config:
        import:
        - optional:configserver:http://localhost:8888
    profiles:
        active: prod

management:
    endpoints:
        web:
            exposure:
                include: "*"
